baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'risotto'
contentdir: content
layoutdir: layouts
publishdir: public
title: STEM Knowledge
description: "The free knowledge initiative!"