baseURL = "https://stem-knowledge-web.github.io/"
languageCode = "en-us"
title = "STEM Knowledge"
paginate = 10

[params]
  description = "A Science Superbook!"
  math = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Courses"
    url = "/courses/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
